name: CI/CD for Airflow Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install apache-airflow

      - name: Run DAG Tests
        run: |
          airflow db init
          airflow dags trigger movie_pipeline_dag
